name: Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: |
          cd AllMyFellasRadio
          dotnet restore
          dotnet build -o build/
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugins
          path: |
            ./AllMyFellasRadio/build/*.dll
          if-no-files-found: "error"
  deploy:
    name: Deployment
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_name == 'main' && github.event_name == 'push'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: plugins
